Backend user validation
gfa-cc-after/Avengers_PET_Clinic pull request #21
Opened 2024-07-17 19:27 UTC by Metemi

Create validation for user in DTO

2024-07-17 19:36 UTC, markkovari reviewed
This is looking fantastic, but I want you to go even further and add one happy and unhappy case at least as tests. 🥺 Please

2024-07-18 05:42 UTC, Metemi commented
https://images.app.goo.gl/uV5KnKGHpNKJ2Hc28

2024-07-18 10:00 UTC, Metemi commented
Well I got 403, I will try fixed it

2024-07-18 10:51 UTC, markkovari requested changes
Just a few nits remanining.

2024-07-18 10:51 UTC, markkovari commented on Backend-API/src/test/java/com/avangers/backendapi/controllers/UserControllerTest.java
> +    private ObjectMapper objectMapper;
```suggestion
    //      objectMapper is used to convert objects to JSON
    @Autowired
    private ObjectMapper objectMapper;
```

If I am not mistaken you might even can autowire it. Not 100%.

2024-07-18 10:51 UTC, markkovari commented on Backend-API/src/test/java/com/avangers/backendapi/controllers/UserControllerTest.java
> +    }
https://www.digitalocean.com/community/tutorials/junit-display-name-displayname you can use the Displayname annotation too.

```suggestion
    @Displayname("should return 200 OK if request is valid")
    @Test
    void shouldRegisterUserWithCorrectNameAndPassword() throws Exception {
        RegisterUserDTO validUser = new RegisterUserDTO("user@example.com", "Abc123456");
        given(userServiceImpl.addUser(validUser)).willReturn(ResponseEntity.ok("Registration was successful"));

        mockMvc.perform(post("/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(validUser)))
                .andExpect(status().isOk());
    }
```

2024-07-18 10:51 UTC, markkovari commented on Backend-API/src/test/java/com/avangers/backendapi/controllers/UserControllerTest.java
> +//        should return 400 BAD REQUEST
Same here.

2024-07-18 10:51 UTC, markkovari commented on Backend-API/src/test/java/com/avangers/backendapi/controllers/UserControllerTest.java
> +    //      setUp method is used to create the objectMapper before each test
Maybe it is just me, but I feel like, your comments are "just describing" the 4 lines below. It is almost exactly as the code. Just a heads-up; if you want to add this comment you commit to maintain it too.

2024-07-18 11:22 UTC, markkovari commented
@Metemi just a little bit of help.

Since we opted in to use spring security, we have 403's everywhere. We need to enable requests to work without authentication. 





And here is an example too:
https://github.com/gfa-cc-after/Pet-Clinic-GilmoreDevs/blob/b5b403661ae1b848b26e0f4164db6c9b60704b93/backend/src/main/java/com/greenfoxacademy/backend/config/SecurityConfig.java#L26-L35

2024-07-18 13:31 UTC, Metemi commented
Thank you Mark I will look at it

2024-07-18 14:18 UTC, markkovari approved these changes

2024-07-18 17:35 UTC, MikeMoudry approved these changes
![image](https://github.com/user-attachments/assets/9ca24db1-c02c-4b6b-8f8a-b67f166a6ddb)

2024-07-18 17:47 UTC, merged