Feat/login page pet clinic
gfa-cc-after/Avengers_PET_Clinic pull request #3
Opened 2024-06-18 19:09 UTC by Metemi

HI, Just want to show what I have done. 
It is Login page.... just in seperated app.  I can than create new branch from main and create new page in pages

2024-06-18 20:34 UTC, Normelik commented on AvengersPetClinic/src/App.tsx
> +            <label className='label'> Passwor:
letter D is missing

2024-06-20 15:33 UTC, Metemi commented on AvengersPetClinic/src/App.tsx
> +            <label className='label'> Passwor:
Letter D added

2024-06-20 17:50 UTC, markkovari commented on AvengersPetClinic/src/App.tsx
> +              ></input>
Noice

![image](https://github.com/gfa-cc-after/Avengers_PET_Clinic/assets/33259514/1f41c52e-5454-4141-8ad1-13a6ac7ba3c2)

2024-06-20 17:50 UTC, markkovari reviewed
Nice

2024-06-20 17:51 UTC, markkovari requested changes
There should be no space there

2024-06-20 17:51 UTC, markkovari commented on AvengersPetClinic/src/App.tsx
> +                <input className='input'
```suggestion
          <div className='inputGroup'>
            <label className='label'>Password: 
                <input className='input'
```

2024-06-20 18:17 UTC, closed without merging