implement login endpoint and login request and response DTOs
gfa-cc-after/Avengers_PET_Clinic pull request #42
Opened 2024-08-10 10:13 UTC by Juraj0101

2024-08-10 17:31 UTC, markkovari commented
@Juraj0101 we have some conflicts here, do you need anyone help from anyone else? Feel free to ping "them" 😉

2024-08-12 13:29 UTC, Normelik approved these changes

2024-08-12 15:02 UTC, markkovari requested changes

2024-08-12 15:02 UTC, markkovari commented on Backend-API/src/main/java/com/avangers/backendapi/services/UserService.java
> +  LoginResponseDTO login(LoginRequestDTO loginRequestDTO);
This method does not follow our convention. (Every other method has the `User` suffix.) It is debatable if we need those or not, but we should follow some conventions.

2024-08-12 15:02 UTC, markkovari commented on Backend-API/src/main/java/com/avangers/backendapi/services/UserServiceImpl.java
> +    throw new RuntimeException("Password is not valid");
The indentation of the method is off here. And (opinion alert) I am not the biggest fa of the comments here neither, but I do not mind them. I see little or no benefits, but more maintainability with them.

2024-08-14 15:04 UTC, markkovari approved these changes

2024-08-14 16:31 UTC, merged