Login page
gfa-cc-after/Avengers_PET_Clinic pull request #5
Opened 2024-06-20 18:56 UTC by Metemi

copyied Login page from last branch

2024-06-20 19:14 UTC, Normelik commented on Pet-Clinic-Frontend/src/pages/Login.css
> +  }
we dont need this :)

2024-06-20 19:17 UTC, Metemi commented on Pet-Clinic-Frontend/src/pages/Login.css
> +  }
it is gone

2024-06-20 19:18 UTC, Normelik reviewed
@Metemi css without using, it the rest of the initial project setup

2024-06-20 19:19 UTC, Normelik approved these changes

2024-06-21 13:51 UTC, Normelik approved these changes

2024-06-22 08:44 UTC, markkovari commented on Pet-Clinic-Frontend/.gitignore
> +yarn-error.log*git
Isn't this a duplication?

2024-06-22 08:45 UTC, markkovari requested changes

2024-06-22 08:45 UTC, markkovari commented on Pet-Clinic-Frontend/.gitignore
> +node_modules
Already added above.

2024-06-22 08:45 UTC, markkovari commented on Pet-Clinic-Frontend/src/pages/Login.tsx
> +          window.location.reload()
We probably we do not want to `console.log` and reloading things with `window.reload`.

2024-06-22 08:51 UTC, markkovari approved these changes

2024-06-22 09:12 UTC, merged